#ifndef XML_AUDIORESAMPLE_ELEMENT_HPP
#define XML_AUDIORESAMPLE_ELEMENT_HPP
#define XML_AUDIORESAMPLE_ELEMENT_NAME       "audioresample"
#define XML_AUDIORESAMPLE_ATTR_QUALITY       "quality"
#define XML_AUDIORESAMPLE_ATTR_FILTER_LENGTH "filter_length"
#endif
