#ifndef XML_GSTRTPJITTERBUFFER_ELEMENT_HPP
#define XML_GSTRTPJITTERBUFFER_ELEMENT_HPP
#define XML_GSTRTPJITTERBUFFER_ELEMENT_NAME         "gstrtpjitterbuffer"
#define XML_GSTRTPJITTERBUFFER_ATTR_LATENCY         "latency"
#define XML_GSTRTPJITTERBUFFER_ATTR_DROP_ON_LATENCY "drop_on_latency"
#define XML_GSTRTPJITTERBUFFER_ATTR_MODE			"mode"
#define XML_GSTRTPJITTERBUFFER_ATTR_PERCENT		    "percent"
#endif
