#ifndef PEER_INFO_CONSTANT
#define PEER_INFO_CONSTANT

#define _PEER_INFO_MAX_IP_STR_SIZE   40
#define _PEER_INFO_MAX_PORT_STR_SIZE 10
#define _PEER_INFO_MAX_UUID_STR_SIZE 255
#define _PEER_VECTOR_MAX_PEER_SIZE 255

#endif
