#define module name
XML_CONFIGURATOR_2_MODULE      := xml_configurator_2_module
XML_CONFIGURATOR_2_MODULE_OBJS :=
MODULES_POOL                   += $(XML_CONFIGURATOR_2_MODULE)


# XML Parser
XML_PARSER_2_PREFIX  := xmlConfig/parser2
XML_PARSER_2_SRC_CPP := $(wildcard $(XML_PARSER_2_PREFIX)/*.cpp)
XML_PARSER_2_OBJ_CPP := $(notdir $(patsubst %.cpp,%.o,$(XML_PARSER_2_SRC_CPP)))
XML_PARSER_2_OBJ_CPP_OUT := $(addprefix $(OUT_DIRS)/,$(XML_PARSER_2_OBJ_CPP))

# XML Profile 2 
XML_PROFILE_2_PREFIX  := xmlConfig/parser2/profiles
XML_PROFILE_2_SRC_CPP := $(wildcard $(XML_PROFILE_2_PREFIX)/*.cpp)
XML_PROFILE_2_OBJ_CPP := $(notdir $(patsubst %.cpp,%.o,$(XML_PROFILE_2_SRC_CPP)))
XML_PROFILE_2_OBJ_CPP_OUT := $(addprefix $(OUT_DIRS)/,$(XML_PROFILE_2_OBJ_CPP))

# XML Attributes 2
XML_ATTRIBUTES_2_PREFIX  := xmlConfig/parser2/attributes
XML_ATTRIBUTES_2_SRC_CPP := $(wildcard $(XML_ATTRIBUTES_2_PREFIX)/*.cpp)
XML_ATTRIBUTES_2_OBJ_CPP := $(notdir $(patsubst %.cpp,%.o,$(XML_ATTRIBUTES_2_SRC_CPP)))
XML_ATTRIBUTES_2_OBJ_CPP_OUT := $(addprefix $(OUT_DIRS)/,$(XML_ATTRIBUTES_2_OBJ_CPP))

# XML elements 2
XML_ELEMENTS_2_PREFIX  := xmlConfig/parser2/elements
XML_ELEMENTS_2_SRC_CPP := $(wildcard $(XML_ELEMENTS_2_PREFIX)/*.cpp)
XML_ELEMENTS_2_OBJ_CPP := $(notdir $(patsubst %.cpp,%.o,$(XML_ELEMENTS_2_SRC_CPP)))
XML_ELEMENTS_2_OBJ_CPP_OUT := $(addprefix $(OUT_DIRS)/,$(XML_ELEMENTS_2_OBJ_CPP))

XML_CONFIGURATOR_2_MODULE_OBJS += $(XML_PARSER_2_OBJ_CPP_OUT)
XML_CONFIGURATOR_2_MODULE_OBJS += $(XML_PROFILE_2_OBJ_CPP_OUT)
XML_CONFIGURATOR_2_MODULE_OBJS += $(XML_ATTRIBUTES_2_OBJ_CPP_OUT)
XML_CONFIGURATOR_2_MODULE_OBJS += $(XML_ELEMENTS_2_OBJ_CPP_OUT)

MODULES_OBJS += $(XML_CONFIGURATOR_2_MODULE_OBJS) 
