#ifndef XML_AUDIOAMPLIFY_ELEMENT_HPP
#define XML_AUDIOAMPLIFY_ELEMENT_HPP
#define XML_AUDIOAMPLIFY_ELEMENT_NAME         "audioamplify"
#define XML_AUDIOAMPLIFY_ATTR_AMPLIFICATION   "amplification"
#define XML_AUDIOAMPLIFY_ATTR_CLIPPING_METHOD "clipping-method"
#endif
