#ifndef SECURITY_LOCK_H
#define SECURITY_LOCK_H
//#define PARAMETER_MANAGER_HIGH_SECURITY_LOCK
//#define BASESTREAM_HIGH_SECURITY_LOCK
//#define RING_BUFFER_HIGH_SECURITY_LOCK
//#define STREAM_RECEPTION_MANAGER_HIGH_SECURITY_LOCK
//#define STREAM_TRANSFER_MANAGER_HIGH_SECURITY_LOCK
//#define XML2_CONFIGURATOR_STREAM_HAHS_MAPPING	
#endif 
