#ifndef XML_STREAM_ELEMENT_HPP
#define XML_STREAM_ELEMENT_HPP
#define XML_STREAM_ELEMENT_NAME "stream"
#define XML_STREAM_ELEMENT_ATTR_ROLE "role"
#define XML_STREAM_ELEMENT_ATTR_NAME "name"
#define XML_STREAM_ELEMENT_ATTR_SLEEP_INTERVAL    "sleep_interval"
#define XML_STREAM_ELEMENT_ATTR_GST_STATE_TIMEOUT "gst_state_timeout"
#define XML_STREAM_ELEMENT_ATTR_TIMEOUT_COUNT     "timeout_count"
#define XML_STREAM_ELEMENT_ATTR_PASSIVE     	  "passive"
#endif

