#ifndef XML_X264ENC_ELEMENT_HPP
#define XML_X264ENC_ELEMENT_HPP
#define XML_X264ENC_ELEMENT_NAME    "x264enc"
#define XML_X264ENC_ATTR_THREADS    "threads"
#define XML_X264ENC_ATTR_PASS       "pass"
#define XML_X264ENC_ATTR_QUANTIZER  "quantizer"
#define XML_X264ENC_ATTR_BYTESTREAM "byte_stream"
#define XML_X264ENC_ATTR_BITRATE    "bitrate"
#define XML_X264ENC_ATTR_VBVBUFCAP  "vbv_buf_capacity"
#define XML_X264ENC_ATTR_MOTION_ESTIMATION "me"
#define XML_X264ENC_ATTR_SUBME      "subme"
#define XML_X264ENC_ATTR_DCT8X8     "dct8x8"
#define XML_X264ENC_ATTR_REF        "ref"
#define XML_X264ENC_ATTR_BFRAMES    "bframes"
#define XML_X264ENC_ATTR_BADAPT     "bAdapt"
#define XML_X264ENC_ATTR_BPYRAMID   "bPyramid"
#define XML_X264ENC_ATTR_WEIGHTB    "weightb"
#define XML_X264ENC_ATTR_SPSID      "spsId"
#define XML_X264ENC_ATTR_TRELLIS    "trellis"
#define XML_X264ENC_ATTR_KEYINTMAX  "keyIntMax"
#define XML_X264ENC_ATTR_CABAC      "cabac"
#define XML_X264ENC_ATTR_QPMIN      "qpMin"
#define XML_X264ENC_ATTR_QPMAX      "qpMax"
#define XML_X264ENC_ATTR_QPSTEP     "qpStep"
#define XML_X264ENC_ATTR_IPFACTOR   "ipFactor"
#define XML_X264ENC_ATTR_PBFACTOR   "pbFactor"
#define XML_X264ENC_ATTR_NOISEREDUCTION  "noiseReduction"
#define XML_X264ENC_ATTR_INTERLACED  "interlaced"
#endif
